version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    command:
      - /bin/bash
      - -c
      - |
        alembic upgrade head && uvicorn app.main:app --forwarded-allow-ips='*' --proxy-headers --host 0.0.0.0 --port 8000
    networks:
      - backend_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    command: >
      celery -A app.core.celery:celery_app worker --loglevel=info
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: