"""sub

Revision ID: 2869e45442d5
Revises: ece6b2e2a17e
Create Date: 2025-09-03 07:11:01.368192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2869e45442d5"
down_revision: Union[str, Sequence[str], None] = "ece6b2e2a17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_subscribed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "users", sa.Column("subscription_id", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("subscription_end", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "cancel_at_period_end",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cancel_at_period_end")
    op.drop_column("users", "subscription_end")
    op.drop_column("users", "subscription_id")
    op.drop_column("users", "is_subscribed")
    # ### end Alembic commands ###
