"""sub addition

Revision ID: 41561399bee5
Revises: 2869e45442d5
Create Date: 2025-09-07 09:12:46.609537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41561399bee5'
down_revision: Union[str, Sequence[str], None] = '2869e45442d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_start', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('liqpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('order_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'order_id')
    op.drop_column('users', 'liqpay_order_id')
    op.drop_column('users', 'subscription_start')
    # ### end Alembic commands ###
